### ISSUE TITLE
A-frame Bug Fixing Contest | WebVR Hack Star

### ISSUE THREAD

**Issue by shahbaz17** [webvr-india/volunteer-contributions#33]
This issue is created to report contributions done by volunteers for the A-frame Bug Fixing Contest | WebVR Hack Star Contest

**Name :**
**Merged PR Link :**

**Comment by ShaguftaMethwani** [comment]
Shagufta Gurmukhdas

1) https://github.com/aframevr/aframe/pull/2780
2) https://github.com/aframevr/aframe/pull/2778
3) https://github.com/aframevr/aframe/pull/2759

**Comment by gurumukhi** [comment]
Ram Dayal Vaishnav
Issue: https://github.com/aframevr/aframe/issues/2633
PR: https://github.com/aframevr/aframe/pull/2642#pullrequestreview-35526633

**Comment by divyam3897** [comment]
Divyam Madaan

PR: https://github.com/aframevr/aframe-site/pull/436
PR: https://github.com/aframevr/aframe-site/pull/437

**Comment by RCMainak** [comment]
Mainak R. Chowdhury

1. https://github.com/aframevr/aframe-site/pull/433

**Comment by gurumukhi** [comment]
Sorry for a very delayed response, we couldn't procure the contest gifts on time because of some changes in Mozilla staff who was assisting us on this.

I see @ShaguftaMethwani & @gurumukhi's all reported PRs are accepted. One of @divyam3897's PR isn't accepted but other one is accpted.

@RCMainak can you please followup with aframe team to get you PR reviewed? Remind them again on PR and ping them on slack also if no one is responding on the PR.

Anyways, Thanks all for your efforts in this contest. I have dropped you messages on telegram for your rewards (please ping me telegram on @ram_gurumukhi if you didn't get my ping yet). We will also celebrate your contribution during Oct's monthly call. Follow the monthly call for more details. Leaving this open in case Mainak can get his PR reviewed before the monthly call.
