### ISSUE TITLE
 Volunteers contributions collection for Q3 2017

### ISSUE THREAD

**Issue by ranjithrajvasam** [webvr-india/volunteer-contributions#35]
Opening this issue as per https://github.com/webvr-india/volunteer-contributions/blob/master/README.md (instead of monthly, created quarterly issue this time).

Volunteers can share their contributions done during Q4 2017 on this issue. While sharing your scenes/projects with us, you can follow the following format -

Create a VR project/scene and share with community-
Name :
Title/Summary of Project / Scene :
Link of Project / Scene :
Remark:

Conduct an event and share about it here-
Name :
Event Name :
Event Date :
Event Location :
Event Link :

Share your blog/media articles with community-
Name:
Blog/Tweet/Article link:
Summary of your media/social media coverage:

Many thanks for your amazing contributions and sharing them with community here!

**Comment by Jyothirmaikottu** [comment]
Name : Jyothirmai Kottu
Title/Summary of Project / Scene :  Christmas Theme
Link of Project / Scene : https://jyothirmaikottu.gitlab.io/chirstmas/

**Comment by BhuvanaMeenakshi** [comment]
Name : Ms. K. Bhuvana Meenakshi
VR projects
1. Title of the Project: Pongal Wishes using WebVR
Summary: To visualize how Pongal is an important festival for Tamilians and also how it is celebrated in different forms in India.
Link of Project: https://bhuvanameenakshi.github.io/Pongal_WebVR_wishes/index.html

2. Title of the Project: Lost Paradise
Summary: This is my first game cum short story which I made with few cartoon characters. It’s about how the prince and princess fine their “Lost Paradise”.
Link of Project: https://bhuvanameenakshi.github.io/Lost_Paradise/index.html
3. Title of the Project: World Lost
Summary: This is another game which I did for the js13Kgames contest. I mainly focused on keeping the memory restricted to less than 13k and succeeded in completing it.
Link of Project: https://bhuvanameenakshi.github.io/World_Lost/index.html
Remark: It was published in js13games under Aframe category. (http://js13kgames.com/entries/world-lost)
4. Title of the Project: Cancer awareness campaign using WebVR
Summary: In order to bring done the rate of cancer affected patients, I made a webVR for people to get an awareness about the deadly disease well in prior. This is aimed to help the kids also to understand about this disease in a more friendly way.
Link of Project: https://bhuvanameenakshi.github.io/Cancer-awareness-campaign/index.html

Events

Event Name : Webinar on A-frame with M.Kumarasamy College of Engg.
Event Date : 01.10.2017
Event Location : Online (hangouts on air)
Event Link : https://youtu.be/zojIKKn8ITI
Blogs
Blog link: https://kbmtechie.wordpress.com/2017/08/03/i-adore-webvr-when-amalgamated-with-gis/
Summary: I gave my ideas on how GIS is improving and necessary in different fields today and also I gave my visions on how WebVR can play a vital role in this.

**Comment by gurumukhi** [comment]
Thanks @Jyothirmaikottu for the cool scene.

Thanks a lot @BhuvanaMeenakshi for amazing scenes, congratulations for 13k games submission & special thanks for the session, I am sure this have benefited the participants (I saw the full video, this is really great).

Thanks to both of you again, your contributions are added to https://wiki.mozilla.org/India/WebVR/. Closing this issue, keep contribuing!
