### ISSUE TITLE
Projects/Scenes created in October 2016

### ISSUE THREAD

**Issue by tushararora** [webvr-india/volunteer-contributions#5]

**Comment by vibhanshuchaudhary** [comment]
Hi everyone
Due to some reason, I did change my Github username from **vibhanshu95** to **vibhanshuchaudhary** . So, the scenes I created in September are now being accessed by new username. I regret for any inconvenience. Link to all those scenes are as follows : 

1. https://vibhanshuchaudhary.github.io/MyVR/scene1.html
2. https://vibhanshuchaudhary.github.io/MyVR/scene2.html
3. https://vibhanshuchaudhary.github.io/MyVR/scene3.html
4. https://vibhanshuchaudhary.github.io/MyVR/scene4.html
5. https://vibhanshuchaudhary.github.io/MyVR/scene5.html
6. https://vibhanshuchaudhary.github.io/MyVR/scene6.html

**Comment by shubhamgeete** [comment]
https://shubhamgeete.github.io/MywebVR/aframe.html
https://shubhamgeete.github.io/MywebVR/webvr_scene3.html
https://shubhamgeete.github.io/MywebVR/scene3.html

**Comment by vibhanshuchaudhary** [comment]
Realistic scene of universe using **animations** and **sound**.
 
https://vibhanshuchaudhary.github.io/MyVR/scene7.html

**Comment by gurumukhi** [comment]
Ram
- http://gurumukhi.github.io/vr-ram
- http://gurumukhi.github.io/vr-office

Tushar
 - http://tushararora.github.io/google-logo-colors-animation/
 - http://tushararora.github.io/solar-system/

**Comment by shahbaz17** [comment]
Thanks all for reporting. All your works are now featured on https://wiki.mozilla.org/India/WebVR/.

**Comment by gurumukhi** [comment]
Hi @ngokevin, have a look at @vibhanshuchaudhary's scene : https://vibhanshuchaudhary.github.io/MyVR/scene7.html. I found this really interesting 👍 :)

**Comment by ngokevin** [comment]
Nice. Would be cool to use a real equirectangular image for the background and 3D models :)

**Comment by mradul2601** [comment]
http://htmlpreview.github.io/?https://github.com/mradul2601/WebVR/blob/master/paranoma/index.html


http://htmlpreview.github.io/?https://github.com/mradul2601/WebVR/blob/master/video/index.html
